# Generated by Django 6.0.2 on 2026-02-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('praenomen', models.CharField(max_length=50)),
                ('nomen', models.CharField(max_length=50)),
                ('cognomen', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
            ],
        ),
    ]
