# Generated by Django 6.0.2 on 2026-02-05 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_alter_author_cognomen_alter_author_language_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='id',
            new_name='abbreviation',
        ),
    ]
