# Generated by Django 6.0.2 on 2026-02-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_rename_id_author_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='author',
            name='abbreviation',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
