# Generated by Django 6.0.2 on 2026-02-06 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_author_id_alter_author_abbreviation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('dialect', models.CharField(blank=True, choices=[('LAT', 'Latin'), ('GRK', 'Greek'), ('HEB', 'Hebrew'), ('ENG', 'English'), ('SKR', 'Sanskrit')], max_length=3)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opera', to='authors.author')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('abbreviation', 'author'), name='unique_work')],
            },
        ),
    ]
