# Generated by Django 6.0.2 on 2026-02-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_opus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='language',
            field=models.CharField(blank=True, choices=[('LAT', 'Latin'), ('GRK', 'Greek'), ('HEB', 'Hebrew'), ('ENG', 'English'), ('SKR', 'Sanskrit')], max_length=3),
        ),
    ]
